version: "3.9"

services:
  rust:
    image: rust:1.71-slim-bullseye
    ports:
      - 8000:8000
    volumes:
      - ..:/workspace:cached
    depends_on:
      - postgres
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
